### ISSUE TITLE
Pointers to Interfaces 的意图

### ISSUE THREAD

**Issue by 63isOK** [xxjwxc/uber_go_guide_cn#16]
## Pointers to Interfaces

You almost never need a pointer to an interface. You should be passing interfaces as values—the underlying data can still be a pointer.

An interface is two fields:

1. A pointer to some type-specific information. You can think of this as "type."
2. Data pointer. If the data stored is a pointer, it’s stored directly. If the data stored is a value, then a pointer to the value is stored.

If you want interface methods to modify the underlying data, you must use a pointer.

读英文时,我猜他的本意应该是表达两点:

- 绝大部分情况下使用接口变量就行,没有特别需要使用接口指针变量的场景,毕竟接口变量底层还是指针
- 可以将对象的值/指针赋值给接口变量,如果需要修改对象的值,那就必须将对象指针赋给接口变量

you must use a pointer.这个pointer应该是指给接口变量赋值时的对象指针. 

我这样理解对吗

**Comment by xxjwxc** [comment]
你可以提一个PR。我合并进master

感谢指正

**Comment by 63isOK** [comment]
好的,正在处理中

**Comment by 63isOK** [comment]
@xxjwxc 你有slack或邮箱/irc吗 不知道能不能占用你一点时间交流一下uber代码规范的问题

**Comment by xxjwxc** [comment]
加我微信吧，我主页有，jnpher
