### ISSUE TITLE
【翻译建议】样式 (style) 是支配我们代码的惯例。

### ISSUE THREAD

**Issue by denglj** [xxjwxc/uber_go_guide_cn#29]
“样式 (style) 是支配我们代码的惯例。”

建议style翻译为“风格”。风格隐含着一个人的思维、文化、知识等因素对其行为、偏好的影响，从而在他的作品中表现出与众不同的特征和性状。

文学家有文风、画家有画风、代码专家当然也有码风咯~

**Comment by xxjwxc** [comment]
请提PR，我合并进去
