### ISSUE TITLE
接收器 (receiver) 与接口 这一节有问题

### ISSUE THREAD

**Issue by xuyang404** [xxjwxc/uber_go_guide_cn#30]
sPtrs := map[int]*S{1: {"A"}}  确定编译器不会报错吗？

**Comment by xxjwxc** [comment]
![image](https://user-images.githubusercontent.com/9114492/102870972-c235c480-4478-11eb-8d60-e5bda1453bd3.png)

亲手实验。没有问题

**Comment by xuyang404** [comment]
> ![image](https://user-images.githubusercontent.com/9114492/102870972-c235c480-4478-11eb-8d60-e5bda1453bd3.png)
> 
> 亲手实验。没有问题

为什么不用指定结构体类型？比如这样：
sPtrs := map[int]*S{1: &S{"A"}}

**Comment by xxjwxc** [comment]
省略写法。他的重点不在构造，在于后边的调用。

**Comment by xuyang404** [comment]
> 省略写法。他的重点不在构造，在于后边的调用。

好的，谢谢解答

**Comment by LoongYoung** [comment]
> 省略写法。他的重点不在构造，在于后边的调用。

省略写法，好隐晦，差点儿没看懂
