### ISSUE TITLE
Interface合理性验证

### ISSUE THREAD

**Issue by wjliu** [xxjwxc/uber_go_guide_cn#31]
```
type LogHandler struct {
  h   http.Handler
  log *zap.Logger
}
var _ http.Handler = LogHandler{}
func (h LogHandler) ServeHTTP(
  w http.ResponseWriter,
  r *http.Request,
) {
  // ...
}
```

上述示例代码中的 `var _ http.Handler = LogHandler{}` 这一句 应该是 `var _ http.Handler = &LogHandler{}`吧，因为要验证是否实现接口，应该是取LogHandler struct的指针进行赋值。 放到Goland等IDE中这行应该直接会飘红了。

**Comment by LoongYoung** [comment]
> ```
> type LogHandler struct {
>   h   http.Handler
>   log *zap.Logger
> }
> var _ http.Handler = LogHandler{}
> func (h LogHandler) ServeHTTP(
>   w http.ResponseWriter,
>   r *http.Request,
> ) {
>   // ...
> }
> ```
> 
> 上述示例代码中的 `var _ http.Handler = LogHandler{}` 这一句 应该是 `var _ http.Handler = &LogHandler{}`吧，因为要验证是否实现接口，应该是取LogHandler struct的指针进行赋值。 放到Goland等IDE中这行应该直接会飘红了。

这段代码其实是为了说明 这句话：对于结构类型。。。

> 对于指针类型（如 *Handler）、切片和映射，这是 nil； 对于结构类型，这是空结构。
